#' @title adjustExprLevel
#' @param x The data list generated by normlizeLibrary() function.
#' @param adjustBy By default, adjust post-IP count by INPUT geneSum. Can also choose "pos" to use current position count to adjust for expression level.
#' @export x The data list now with IP-count adjusted for expression level added
adjustExprLevel <- function(x,adjustBy = "geneSum"){
  
  gene.size <- t( apply(x$geneSum,1,function(x){x/mean(x)}) )
  gene.size.factor <- gene.size[x$geneBins$gene,]
  
  if(adjustBy == "geneSum"){
    ip_norm_geneSum <- x$norm.ip/gene.size.factor
    ip_norm_geneSum <- round(ip_norm_geneSum)
    na.flag <- apply(ip_norm_geneSum,1, function(x){any(is.na(x)) | any(is.infinite(x))})
    ip_norm_geneSum <-  ip_norm_geneSum[!na.flag,]
    x <- c(x,list('ip_adjExpr'=ip_norm_geneSum))
  }else if(adjustBy == "pos"){
    pos.size <-  t( apply(x$norm.input,1,function(x){x/mean(x)}) )
    ip_norm_pos <- x$norm.ip/pos.size
    ip_norm_pos <- round(ip_norm_pos)
    na.flag <- apply(ip_norm_pos,1, function(x){any(is.na(x)) | any(is.infinite(x))})
    ip_norm_pos <-  ip_norm_pos[!na.flag,]
    x <- c(x,list('ip_adjExpr'=ip_norm_pos))
  }else{
    stop("Must adjust by \"geneSum\" or by \"pos\"...")
  }
  return(x)
}